### ISSUE TITLE
Does not work with app_name

### ISSUE THREAD

**Issue by patricktran159** [spapas/django-generic-scaffold#2]
Hi, 
when I set app_name in my urls.py, the tag {% url urls.create %} stopped working in my template. 
Please help.

**Comment by spapas** [comment]
Hello @patricktran159 can you be a little more specific? Where do you set the ``app_name`` in your ``urls.py``? Could you provide a snippet maybe? Also  what do you mean that the {% url urls.create %} stopped working. Does it throw an exception or it returns nothing?

**Comment by spapas** [comment]
Closing because of no feedback.

**Comment by luk156** [comment]
if you set app_name in your urls.py for exampke app_name='hello' the url name is prefixed with hello:
