### ISSUE TITLE
Imagefield in models not working

### ISSUE THREAD

**Issue by Ritace** [spapas/django-generic-scaffold#3]
Hi there. I have a model as follows:
```
class FoodType(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='food_types')
    name = models.CharField(max_length = 100)
    background_image = models.ImageField(upload_to='uploads/',blank = True)
    @property
    def model_name(self):
        return "FoodType"
    def __str__(self):
        
        return self.name
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('foodtypes_menu_foodtype_list')
```
My Crud Manager class look like 

```
class FoodTypeCrudManager(CrudManager):
    model = FoodType
    prefix = 'foodtypes'
```
I don't know why but the imageUploadField in not working for some reason. I couldn't find out the cause. I googled and didn't find anything. The field is showing in form but whenever I upload an image the image is not uploaded at all. I can't find the image in upload directory too.

**Comment by spapas** [comment]
Please notice that your `<form>` needs to have the `enctype="multipart/form-data"` attribute in order to upload files https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/#basic-file-uploads

**Comment by Ritace** [comment]
Thanks man it worked. I think it is good idea to add enctype="multipart/form-data" in default form.

**Comment by spapas** [comment]
I think (not sure why) it should not be added to non file upload forms. This is a very common problem with Django (many people are surprised that their file uploads are not working) and I don't think there's a good solution for including the attribute only on file forms...
